# Header
menu:
  首页: /
  前端: /categories/front-end
  后端: /categories/back-end
  通识: /categories/language
  标签: /tags
  归档: /archives
  关于: /about

# Content
excerpt_link: 阅读更多
content_max_width: 800px

# Sidebar
author:
  name: Yuanliang
  work: Programmer &amp; Engineer
  location: Shanghai, China
  avatar_url: /images/avatar.jpg

# Links:
links:
  - svg: ./source/svg/github.svg
    url: https://github.com/woowyl
  - svg: ./source/svg/weibo.svg
    url: http://weibo.com/woowyl

#blogroll:
blogroll:
  - name: '文杰的博客'
    url: 'https://tony-piao.github.io/'
  - name: '程凯的博客'
    url: 'https://chengkai.wang/'
# github comment 
git_commit:
  enable: true
  client_id: 0da1f66fc44b769a7531
  client_secret: 567ec8a984c0f8fdcfd505b556e0ef16d99eab19
  repo: woowyl.github.io
  owner: woowyl
  admin:
  - woowyl
  per_page: 10

# Baidu
baidu:
  id: 948c1e123cc90fe559dca9cb0d07bbab

# Miscellaneous
favicon: /images/favicon.ico

# Archive page setting
archive_generator:
  per_page: 15
  order_by: -date