# Header
menu:
  首页: /
  前端: /categories/front-end
  后端: /categories/back-end
  标签: /tags
  归档: /archives
  关于: /about

# Content
excerpt_link: 阅读更多
content_max_width: 800px

# Sidebar
author:
  name: Yuanliang
  work: Programmer &amp; Engineer
  location: Shanghai, China
  avatar_url: /images/avatar.jpg

# Links:
links:
  - svg: ./source/svg/github.svg
    url: https://github.com/woowyl
  - svg: ./source/svg/weibo.svg
    url: http://weibo.com/woowyl

# github comment 
git_commit:
  enable: true
  client_id: 7fbe80427f54741e289f
  client_secret: f34ed5fd92e54c9000bd37ba951948cb939deff5
  repo: woowyl.github.io
  owner: woowyl
  admin:
  - woowyl
  per_page: 10

# Baidu
baidu:
  id: 948c1e123cc90fe559dca9cb0d07bbab

# Miscellaneous
favicon: /images/favicon.ico